// Polyfill DOMParser (three's 3MFLoader requires one; in the browser it is native).
import { JSDOM } from 'jsdom'
globalThis.DOMParser = new JSDOM().window.DOMParser

import JSZip from 'jszip'
import { use3mfParser, computeStreamedGeometry } from '../composables/use3mfParser.js'
import { streamMeshObjects, accumulateMeshMeasurement } from '../composables/useMeshVolume.js'
import { computeWear, wearBracket } from '../composables/useWearCost.js'

const CONTENT_TYPES = `<?xml version="1.0"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
</Types>`

const RELS = `<?xml version="1.0"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Target="/3D/3dmodel.model" Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>
</Relationships>`

const CUBE_OBJECT = `<object id="1" type="model">
      <mesh>
        <vertices>
          <vertex x="0" y="0" z="0"/><vertex x="10" y="0" z="0"/><vertex x="10" y="10" z="0"/><vertex x="0" y="10" z="0"/>
          <vertex x="0" y="0" z="10"/><vertex x="10" y="0" z="10"/><vertex x="10" y="10" z="10"/><vertex x="0" y="10" z="10"/>
        </vertices>
        <triangles>
          <triangle v1="0" v2="2" v3="1"/><triangle v1="0" v2="3" v3="2"/>
          <triangle v1="4" v2="5" v3="6"/><triangle v1="4" v2="6" v3="7"/>
          <triangle v1="0" v2="1" v3="5"/><triangle v1="0" v2="5" v3="4"/>
          <triangle v1="1" v2="2" v3="6"/><triangle v1="1" v2="6" v3="5"/>
          <triangle v1="2" v2="3" v3="7"/><triangle v1="2" v2="7" v3="6"/>
          <triangle v1="3" v2="0" v3="4"/><triangle v1="3" v2="4" v3="7"/>
        </triangles>
      </mesh>
    </object>`

const CUBE = `<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <resources>
    ${CUBE_OBJECT}
  </resources>
  <build>
    <item objectid="1"/>
  </build>
</model>`

const CUBE_BUILD_TRANSFORM = CUBE.replace('</model>',
  `  <item objectid="1" transform="100 0 0 0 100 0 0 0 100 50 0 0"/>\n</model>`)

const SLICE_INFO = `<config>
  <plate>
    <metadata key="index" value="1"/>
    <metadata key="weight" value="12.34"/>
    <metadata key="time" value="3600"/>
    <filament id="0" type="PLA" color="#FF0000" used_m="2.8" used_g="9.1"/>
  </plate>
</config>`

const GCODE = `; generated by OrcaSlicer
; estimated printing time (normal mode) = 2h 14m 31s
; filament used [g] = 4.56
; filament used [mm3] = 1234.0
; total_weight = 20.0
G1 X0 Y0`

function makeBlob (name, buf) {
  return Object.assign(new Blob([buf]), { name })
}

async function build3mf (name, files) {
  const zip = new JSZip()
  zip.file('[Content_Types].xml', CONTENT_TYPES)
  zip.file('_rels/.rels', RELS)
  for (const [path, content] of Object.entries(files)) zip.file(path, content)
  const buf = await zip.generateAsync({ type: 'nodebuffer' })
  return makeBlob(name, buf)
}

function assert (cond, label, actual) {
  if (!cond) {
    console.error(`FAIL: ${label} — got`, actual)
    process.exitCode = 1
  } else {
    console.log(`ok: ${label}`)
  }
}

const raw = await build3mf('cube.3mf', { '3D/3dmodel.model': CUBE })
const rawResult = await use3mfParser(raw)
assert(rawResult.mode === 'raw', 'raw cube = raw mode', rawResult.mode)
assert(Math.abs(rawResult.geometry.volumeCm3 - 1) < 1e-3, 'cube volume = 1 cm³', rawResult.geometry.volumeCm3)
assert(rawResult.geometry.bbox?.x === 10 && rawResult.geometry.bbox?.y === 10 && rawResult.geometry.bbox?.z === 10, 'cube bbox 10×10×10', rawResult.geometry.bbox)
assert(rawResult.geometry.surfaceAreaMm2 === 600, 'cube surface area = 600 mm²', rawResult.geometry.surfaceAreaMm2)

// Shell-and-infill model (same formula ResultsPanel uses):
// 0.5mm shell wraps the surface solid; interior is filled at infill%.
const shellCube = Math.min(1, (rawResult.geometry.surfaceAreaMm2 * 0.5) / 1000)
const effectiveCube = shellCube + (1 - shellCube) * (20 / 100)
const wallWeightCube = effectiveCube * 1.24
assert(Math.abs(effectiveCube - 0.44) < 1e-9, 'cube wall model: 0.5mm shell + 20% infill = 0.44 cm³ effective', effectiveCube)
assert(Math.abs(wallWeightCube - 0.5456) < 1e-9, 'cube wall model PLA weight = 0.5456 g (vs 0.248 g flat-infill)', wallWeightCube)

assert(rawResult.slicer.weightG == null, 'raw cube has no slicer weight', rawResult.slicer.weightG)
assert(rawResult.buildItems === 1, 'buildItems = 1', rawResult.buildItems)
assert(rawResult.objectCount === 1, 'objectCount = 1 (DOMParser available)', rawResult.objectCount)

const transformed = await build3mf('cube-moved.3mf', { '3D/3dmodel.model': CUBE_BUILD_TRANSFORM })
const moved = await use3mfParser(transformed)
assert(Math.abs(moved.geometry.volumeCm3 - 1) < 1e-3, 'transformed cube volume still 1 cm³', moved.geometry.volumeCm3)
assert(Math.abs(moved.geometry.bbox.x - 10) < 1e-6, 'transformed cube bbox.x still 10mm (origin-independent)', moved.geometry.bbox)
assert(Math.abs(moved.geometry.surfaceAreaMm2 - 600) < 1e-6, 'transformed cube surface area still 600 mm²', moved.geometry.surfaceAreaMm2)

const sliced = await build3mf('sliced.3mf', {
  '3D/3dmodel.model': CUBE,
  'Metadata/slice_info.config': SLICE_INFO
})
const slicedResult = await use3mfParser(sliced)
assert(slicedResult.mode === 'sliced', 'sliced package = sliced mode', slicedResult.mode)
assert(slicedResult.slicer.weightG === 12.34, 'slice_info weight = 12.34g (plate weight beats per-filament)', slicedResult.slicer.weightG)
assert(slicedResult.slicer.lengthM === 2.8, 'slice_info used_m = 2.8m', slicedResult.slicer.lengthM)
assert(slicedResult.slicer.filamentTypes.includes('PLA'), 'filament type PLA', slicedResult.slicer.filamentTypes)
assert(slicedResult.slicer.colors.includes('#FF0000'), 'filament color extracted', slicedResult.slicer.colors)
assert(slicedResult.geometry.volumeCm3 === 1, 'sliced package still has geometry', slicedResult.geometry.volumeCm3)
assert(slicedResult.slicer.durationH === 1, 'slice_info time (3600s) -> 1h', slicedResult.slicer.durationH)

const withGcode = await build3mf('gcode.3mf', {
  '3D/3dmodel.model': CUBE,
  'Metadata/slice_info.config': SLICE_INFO,
  'Metadata/plate_1.gcode': GCODE
})
const gcodeResult = await use3mfParser(withGcode)
assert(gcodeResult.mode === 'sliced', 'gcode package = sliced', gcodeResult.mode)
assert(gcodeResult.slicer.weightG === 12.34, 'slice_info wins over gcode (no double count)', gcodeResult.slicer.weightG)
assert(gcodeResult.slicer.plates === 1, '1 plate detected', gcodeResult.slicer.plates)
assert(gcodeResult.slicer.durationH === 1, 'slice_info time wins over gcode human format', gcodeResult.slicer.durationH)

const gcodeOnly = await build3mf('gcode-only.3mf', {
  '3D/3dmodel.model': CUBE,
  'Metadata/plate_1.gcode': GCODE
})
const gcodeOnlyResult = await use3mfParser(gcodeOnly)
assert(gcodeOnlyResult.mode === 'sliced', 'gcode-only = sliced', gcodeOnlyResult.mode)
assert(gcodeOnlyResult.slicer.weightG === 20, 'gcode total_weight = 20g', gcodeOnlyResult.slicer.weightG)
assert(gcodeOnlyResult.slicer.volumeCm3 === 1.234, 'gcode mm3 -> cm3', gcodeOnlyResult.slicer.volumeCm3)
assert(Math.abs(gcodeOnlyResult.slicer.durationH - 2.241944) < 1e-3, 'gcode "2h 14m 31s" -> 2.242h', gcodeOnlyResult.slicer.durationH)

const bad = new Blob(['this is not a zip file'])
bad.name = 'broken.3mf'
try {
  await use3mfParser(bad)
  assert(false, 'corrupted file throws', 'no throw')
} catch (err) {
  assert(err.code === 'invalid-archive', 'corrupted file -> invalid-archive', err.code)
}

// Streaming mesh fallback (huge meshes that trip three's ~512 MB string cap)
const EXTERNAL_OBJECT = CUBE_OBJECT.replace('id="1"', 'id="7"').replace('<object', '<object transform="1 0 0 0 1 0 0 0 1 50 0 0"')
const EXTERNAL_PART = `<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <resources>
    ${EXTERNAL_OBJECT}
  </resources>
</model>`

const COMPONENT_PRIMARY = `<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
 <resources>
  <object id="10">
   <components>
    <component objectid="7" path="/3D/Objects/ext.model" transform="1 0 0 0 1 0 0 0 1 0 0 0"/>
   </components>
  </object>
 </resources>
 <build><item objectid="10"/></build>
</model>`

const extZip = new JSZip()
extZip.file('[Content_Types].xml', CONTENT_TYPES)
extZip.file('_rels/.rels', RELS)
extZip.file('3D/3dmodel.model', COMPONENT_PRIMARY)
extZip.file('3D/Objects/ext.model', EXTERNAL_PART)
const extBuf = await extZip.generateAsync({ type: 'nodebuffer' })
const extLoader = await JSZip.loadAsync(extBuf)
const extModelEntries = Object.values(extLoader.files).filter(e => !e.dir && /\.model$/i.test(e.name))
const streamed = await computeStreamedGeometry(extLoader, extModelEntries, { file: extLoader.files['3D/3dmodel.model'] })
assert(Math.abs(streamed.volumeCm3 - 1) < 1e-3, 'streamed component cube volume = 1 cm³ (translation-invariant)', streamed.volumeCm3)
assert(Math.abs(streamed.surfaceAreaMm2 - 600) < 1e-3, 'streamed component cube area = 600 mm²', streamed.surfaceAreaMm2)
assert(Math.abs(streamed.bbox.x - 10) < 1e-6, 'streamed cube bbox.x = 10mm', streamed.bbox)

// Scaled component: 2× → volume ×8, area ×4
const SCALED_PRIMARY = COMPONENT_PRIMARY.replace('transform="1 0 0 0 1 0 0 0 1 0 0 0"', 'transform="2 0 0 0 2 0 0 0 2 0 0 0"')
extZip.file('3D/3dmodel.model', SCALED_PRIMARY)
const scaledBuf = await extZip.generateAsync({ type: 'nodebuffer' })
const scaledLoader = await JSZip.loadAsync(scaledBuf)
const scaledModelEntries = Object.values(scaledLoader.files).filter(e => !e.dir && /\.model$/i.test(e.name))
const scaledStream = await computeStreamedGeometry(scaledLoader, scaledModelEntries, { file: scaledLoader.files['3D/3dmodel.model'] })
assert(Math.abs(scaledStream.volumeCm3 - 8) < 1e-3, 'streamed scaled cube volume = 8 cm³', scaledStream.volumeCm3)
assert(Math.abs(scaledStream.surfaceAreaMm2 - 2400) < 1e-3, 'streamed scaled cube area = 2400 mm²', scaledStream.surfaceAreaMm2)

// streamMeshObjects handles partial tags split across the 1 MB chunk boundary
// and long non-tag runs (metadata) without losing data.
const streamedObjects = await streamMeshObjects({ async: async () => new Uint8Array(await new Blob([EXTERNAL_PART]).arrayBuffer()) })
const obj7 = streamedObjects.get(7)
const identity = new (await import('three')).Matrix4()
const measured = accumulateMeshMeasurement(obj7.positions, obj7.triangles, identity)
assert(Math.abs(measured.volume / 1000 - 1) < 1e-6, 'streamMeshObjects volume = 1 cm³', measured.volume / 1000)
assert(Math.abs(measured.area - 600) < 1e-6, 'streamMeshObjects area = 600 mm²', measured.area)

// Printer wear-and-tear model (composables/useWearCost.js)
const b = p => wearBracket(p)
assert(b(null) == null && b(0) == null && b(-5) == null, 'wearBracket ignores missing/zero/negative prices', b(null))
const bounds = [[300, 3500, 0.25], [301, 5000, 0.30], [600, 5000, 0.30], [601, 6000, 0.35], [1000, 6000, 0.35], [1001, 8000, 0.40], [2000, 8000, 0.40], [2001, 10000, 0.50]]
for (const [price, hours, pct] of bounds) {
  const br = wearBracket(price)
  assert(br.hours === hours && br.maintenancePct === pct, `wearBracket €${price}-> ${hours}h / ${Math.round(pct * 100)}%`, br)
}
assert(computeWear({ price: null, timeH: 5 }) == null && computeWear({ price: 500, timeH: null }) == null, 'computeWear needs both price and time', computeWear({ price: null, timeH: 5 }))
const wear500 = computeWear({ price: 500, timeH: 4.7 })
assert(wear500.lifespanHours === 5000 && wear500.maintenancePct === 0.30, '€500 printer: 5.000h life, 30% maintenance', wear500)
assert(Math.abs(wear500.maintenanceCost - 150) < 1e-9, '€500 maintenance = €150', wear500.maintenanceCost)
assert(Math.abs(wear500.maintenanceCoefficient - 1.3) < 1e-9, '€500 maintenance coefficient = 1.30', wear500.maintenanceCoefficient)
assert(Math.abs(wear500.totalLifetimeCost - 650) < 1e-9, '€500 total lifetime cost = €650', wear500.totalLifetimeCost)
assert(Math.abs(wear500.wearCostPerHour - 0.13) < 1e-9, '€500 wear = €0.13/h', wear500.wearCostPerHour)
assert(Math.abs(wear500.printWearCost - 0.611) < 1e-9, '€500 print (4.7h) wear = €0.611', wear500.printWearCost)
const wearCheap = computeWear({ price: 200, timeH: 10 })
assert(Math.abs(wearCheap.wearCostPerHour - (250 / 3500)) < 1e-9, '€200 wear per hour = 250/3500', wearCheap.wearCostPerHour)
assert(Math.abs(wearCheap.printWearCost - 2500 / 3500) < 1e-9, '€200 print (10h) wear', wearCheap.printWearCost)
const wearPro = computeWear({ price: 3000, timeH: 2.5 })
assert(Math.abs(wearPro.maintenanceCost - 1500) < 1e-9, '€3000 maintenance = €1500 (50%)', wearPro.maintenanceCost)
assert(Math.abs(wearPro.wearCostPerHour - 0.45) < 1e-9, '€3000 wear = €0.45/h', wearPro.wearCostPerHour)
assert(Math.abs(wearPro.printWearCost - 1.125) < 1e-9, '€3000 print (2.5h) wear = €1.125', wearPro.printWearCost)

// Optional lifespan / maintenance overrides replace the bracket estimate.
const wearOverride = computeWear({ price: 500, timeH: 4.7, lifespanHours: 4000, maintenancePct: 0.2 })
assert(wearOverride.lifespanHours === 4000 && wearOverride.maintenancePct === 0.2, 'override life+maintenance used', wearOverride)
assert(Math.abs(wearOverride.maintenanceCost - 100) < 1e-9, 'override maintenance = €100 (20%)', wearOverride.maintenanceCost)
assert(Math.abs(wearOverride.maintenanceCoefficient - 1.2) < 1e-9, 'override coefficient = 1.20', wearOverride.maintenanceCoefficient)
assert(Math.abs(wearOverride.totalLifetimeCost - 600) < 1e-9, 'override lifetime cost = €600', wearOverride.totalLifetimeCost)
assert(Math.abs(wearOverride.wearCostPerHour - 0.15) < 1e-9, 'override wear = €0.15/h', wearOverride.wearCostPerHour)
assert(Math.abs(wearOverride.printWearCost - 0.705) < 1e-9, 'override print (4.7h) wear = €0.705', wearOverride.printWearCost)
const wearZeroMaint = computeWear({ price: 500, timeH: 2, maintenancePct: 0 })
assert(Math.abs(wearZeroMaint.maintenanceCost) < 1e-9 && wearZeroMaint.maintenanceCoefficient === 1, '0% maintenance override is honoured', wearZeroMaint)
assert(Math.abs(wearZeroMaint.printWearCost - 0.2) < 1e-9, 'no-maintenance wear = 500/5000×2 = €0.20', wearZeroMaint.printWearCost)
const wearNullOverrides = computeWear({ price: 500, timeH: 4.7, lifespanHours: null, maintenancePct: null })
assert(wearNullOverrides.lifespanHours === 5000 && wearNullOverrides.maintenancePct === 0.30, 'null overrides fall back to bracket', wearNullOverrides)
const wearRawPct = computeWear({ price: 299, timeH: 1.29, lifespanHours: 3500, maintenancePct: 25 })
assert(wearRawPct.maintenancePct === 0.25 && Math.abs(wearRawPct.maintenanceCost - 74.75) < 1e-9, 'raw percent (25) normalised to fraction', wearRawPct)
const wearOnlyPrice = computeWear({ price: 299, timeH: 1.29 })
assert(wearOnlyPrice.maintenancePct === 0.25 && Math.abs(wearOnlyPrice.maintenanceCost - 74.75) < 1e-9, 'price-only wear uses 25% bracket maintenance', wearOnlyPrice)
assert(Math.abs(wearOnlyPrice.printWearCost - ((299 + 74.75) / 3500) * 1.29) < 1e-9, 'price-only wear amount', wearOnlyPrice.printWearCost)